output_dir: development
depth: 4  # depth of each patway
dt: 0.01  # learning rate
T: 1000  # Number of epochs
eps: 0.01  # scale of noise on diag
add_noise_diag_scale: 0.1
deficit_length: 150
deficit_start_list: [ 0, 400, 750 ]
nonlin: null
use_deficit: True
pathway_width: 100
seed: 0

