!!python/object:argparse.Namespace
T_critical_list:
- 0
- 1000
- 5000
- 10000
- 20000
- 40000
- 60000
- 80000
- 100000
depth: 2
epoch_continue: 30000
hidden_dim: 100
init_scale: 0.001
initialization: gaussian
matrix_dim: 100
ntrain_samples: 1000
ntrain_samples2: 1500
optimizer: sgd
output_dir: output_nov17/NUM-EXAMPLES-EXP_depth=2-ntrain=1000-ntrain2=1500_rank1=5_epochCont=30000_seed=1_initScale=0.001_lr=0.2_opt=sgd
rank1: 5
rank2: 5
seed: 1
sgd_lr: 0.2
